language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install django"
  - "pip install selenium"
# command to run tests
script: ./run-tests.sh
