language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install django"
  - "pip install selenium"
  - "pip install -r requirements.txt"
# command to run tests
script: ./run-tests.sh
notifications:
  email:
    recipients:
      - voong.david@gmail.com 
      - mark@teos.co.uk
    on_success: change
    on_failure: always
